# Setting host
- hosts: localhost
  gather_facts: false
#Variables
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: hello-go
    image_tag: latest
    replicas: 4
# Pre-Tasks to validate if Minikube is running
  pre_tasks:
    - name: Kobo Minikube's status.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
    # Otherwise will start minikube
    - name: Start Minikube if it's not running.
      command: minikube start
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"
# Check existing images
  tasks:
    - name: Get existing image hash.
      shell: |
        eval $(minikube docker-env)
        docker images -q {{ image_name }}
      register: image_hash
      changed_when: false
# Otherwise will create an image from Dockerfile location
    - name: Build image if it's not already built.
      shell: |
        eval $(minikube docker-env)
        docker build -t {{ image_name }} ../kobo360app 
      when: not image_hash.stdout
# Create Kubernetes resources to run Hello Go.
    - name: Create a Deployment for kobo360app.
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: kobo360
            namespace: default
          spec:
            replicas: "{{ replicas }}"
            selector:
              matchLabels:
                app: kobo360app
            template:
              metadata:
                labels:
                  app: kobo360app
              spec:
                containers:
                - name: display localhost
                  image: "{{ image_name }}:{{ image_tag }}"
                  imagePullPolicy: IfNotPresent
                  ports:
                  - containerPort: 8180
# Create Kubernetes Service (DNS required)
    - name: Create a Service for kobo360app.
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: hello-go
            namespace: default
          spec:
            type: LoadBalancer
            ports:
            - port: 8180
              targetPort: 8180
            selector:
              app: hello-go
post_tasks:
    #Example export using minikube services
    - name: Expose kobo360app on the host via Minikube.
      command: minikube service kobo360app --url=true
      changed_when: false
      register: minikube_service
    - debug:
        msg: "kobo360app URL: {{ minikube_service['stdout_lines'][0] }}"
- name: Verify kobo360app is responding.
      uri:
        url: "{{ minikube_service['stdout_lines'][0] }}/test"
        return_content: true
      register: kobo360app_response
      failed_when: "'/test' not in kobo360app_response.content"
- debug:
        msg: "Testing URL kobo360app Requested: {{kobo360app_response.content}} Status: {{kobo360app_response.status}}"
